In [1]:
import numpy as np

1)

In [6]:
arr1 = np.array([0,1,2,3,4,0,0,5,6])
arr2 = np.array([0,1.01,2,0,3,4.02,5,5,6.06])
print(arr1.shape)
print(arr2.shape)

(9,)
(9,)


In [3]:
arr1==0

array([ True, False, False, False, False,  True,  True, False, False])

2)

In [4]:
arr1>0

array([False,  True,  True,  True,  True, False, False,  True,  True])

3)

In [20]:
print(np.allclose(arr1,arr2))
print(np.allclose(arr1,arr2,atol = 0.01))
print(np.allclose(arr1,arr2,atol = 5))

False
False
True


4)

In [21]:
arr1=np.ones(10)
arr2=np.zeros(10)
arr3=5*np.ones(10)
arr4 = np.hstack((arr1, arr2))
arr5 = np.hstack((arr4, arr3))
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5)

In [22]:
arr1=np.arange(30,71)
arr1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

6)

In [24]:
arr1=np.identity(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7)

In [25]:
arr1=np.random.rand(1)
arr1

array([0.47739203])

8)

In [26]:
arr1=np.random.rand(15)
arr1

array([0.06518124, 0.39755012, 0.60682774, 0.99765103, 0.56254418,
       0.72316564, 0.98048906, 0.6488193 , 0.22884984, 0.56828136,
       0.49643973, 0.14425366, 0.97953556, 0.17474817, 0.39088118])

9)

In [28]:
arr1 = np.arange(15,56)
arr1[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

10)

In [31]:
arr1=np.random.randint(0, 11,5)
arr1

array([3, 1, 4, 2, 9])

11)

In [43]:
arr1 = np.ones([10,10])
for i in range(1,9):
  arr1[i,1:-1]=0
arr1[9]=1
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

12)

In [44]:
arr1 = np.zeros([5,5])
for i in range(5):
    arr1[i, i] = i+1
arr1

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

13)

In [46]:
arr1 = np.zeros([4,4])
arr1[::2, 1::2] = 1
arr1[1::2,0::2]=1
arr1

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

14)

In [47]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
np.savez_compressed('file.npz', array1=arr1, array2=arr2)
data = np.load('file.npz')
new_arr1 = data['array1']
new_arr2 = data['array2']
print("Loaded Array 1:")
print(new_arr1)
print("\nLoaded Array 2:")
print(new_arr2)

Loaded Array 1:
[1 2 3 4]

Loaded Array 2:
[5 6 7 8]


15)

In [48]:
arr1 = np.random.rand(40)
arr1

array([0.71263168, 0.10366105, 0.60214546, 0.64273737, 0.64554321,
       0.52910441, 0.06450099, 0.28065239, 0.40014689, 0.50737469,
       0.42984419, 0.01396396, 0.13396818, 0.18439353, 0.16727542,
       0.02879408, 0.26863464, 0.1609817 , 0.20712166, 0.50468184,
       0.47149058, 0.72920485, 0.97065276, 0.20384423, 0.70834413,
       0.12680869, 0.08326058, 0.49535589, 0.36941717, 0.77729835,
       0.48181447, 0.3653205 , 0.93491121, 0.38338857, 0.28760607,
       0.91756406, 0.93078167, 0.9811232 , 0.86188277, 0.88785217])

16)

In [52]:
x = int(input("Please enter a number: "))
arr1 = np.random.randint(20,size=20)
arr1[arr1>x]

Please enter a number: 10


array([15, 14, 13, 19, 14, 18])